# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.JS initialize & install dependencies 

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
      with:
        repository: Beefalo-Cultist/Osmium-Chalice

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
        
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
    - run: npm install --force --package-lock-only  
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: install packages 
      run: |
        npm install
      
    - name: Add & Commit
      run: |
          touch tempoveride.ovr
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Initialized Node.js & installed dependencies"
          git push --force
    - name: Cleanup
      run: |
          git rm tempoveride.ovr
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deleted temp file"
          git push --force
          
    - name: Glitch Project Sync
      uses: kanadgupta/glitch-sync@v2.1.0
      with:
    # Auth token for your Glitch Project
        auth-token: 4736b75f-f7f2-4278-99a2-cca5e20d7d6e
    # ID of your Glitch Project
        project-id: 22e40e90-8a24-4c80-823a-b8f848da0662
    

      
    
  
      
